trigger:
- master

pool:
  vmImage: ubuntu-22.04

variables:
  buildConfiguration: 'Release'
  outputFolder: '$(Build.ArtifactStagingDirectory)/publicacao'

steps:

# Etapa opcional: conferir versão do .NET
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restaurar dependências
- task: DotNetCoreCLI@2
  displayName: 'Restaurar pacotes NuGet'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Build do projeto
- task: DotNetCoreCLI@2
  displayName: 'Build do projeto'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Publicação para pasta local
- task: DotNetCoreCLI@2
  displayName: 'Publicar aplicação'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(outputFolder)'
    zipAfterPublish: true

# Publicar como artefato do pipeline
- task: PublishBuildArtifacts@1
  displayName: 'Publicar artefato'
  inputs:
    PathtoPublish: '$(outputFolder)'
    ArtifactName: 'ConsultaCepWeb'
